### ISSUE TITLE
[FEATURE REQUEST] Please include Linux build instructions

### ISSUE THREAD

**Issue by CHJ85** [BRH-Media/PlexDL#10]
Hi there. I'm interested in using this app.
But there aren't any build instructions or pre-packed release for Linux.
So do you think you could please provide build instructions please?
Thanks.

**Comment by Brhsoftco** [comment]
Hi there!

Thankyou for your interest in the package :) Unfortunately, at this stage PlexDL relies on a lot of Windows-specific features and interactions. Specifically, it is built on the .NET Framework. However, interest in a Linux-functioning version has not been significantly high to warrant a port to .NET (.NET Core) which would enable multi-platform usage. If you're willing to wait for a little while, we can begin works on a Linux port.

**Comment by CHJ85** [comment]
Sounds great. Thank you!

**Comment by Brhsoftco** [comment]
Greetings! I’ll be closing this issue as work on PlexDL will now be limited to the Windows platform due to the amount of effort required to port to the new .NET framework.

**Comment by CHJ85** [comment]
Okay. Thanks anyway.
But the .NET library is on Linux too.
Is it not?

**Comment by Brhsoftco** [comment]
There’s two variants of the .NET architecture; the now-legacy `.NET Framework` and the `.NET` ecosystem, which includes `.NET Core`, `.NET Portable` and of course, the amalgamation of these which is known collectively as `.NET`. The original framework is only truly compatible with Windows, which is what PlexDL is built with.

To allow the system to run on Linux, a port of the entire codebase would be required as `.NET` (as an architecture itself) is the only version that works with Linux.

**Comment by CHJ85** [comment]
I see. Thanks for explaining. 
Have a nice day.
