### ISSUE TITLE
[FEATURE REQUEST] Multiple movies download at time

### ISSUE THREAD

**Issue by teo417** [BRH-Media/PlexDL#4]
Hi, I'm asking if you can develop a way to download movies automatically, without having to choose the movie every time one is downloaded. For example downloading an entire library.

**Comment by Brhsoftco** [comment]
Hi @teo417, thanks for your interest! The download system in PlexDL is a bit wonky, and unfortunately that means it doesn't include a queuing system.

This is a much-requested feature, and I can assure you that an implementation is on the way. For example, did you know you can download an entire season of episodes? This functionality (but with movies) is coming to PlexDL potentially via a 'Download Manager' interface.

It is going to take some time, however.
